### ISSUE TITLE
Small issue with cache hit ratio

### ISSUE THREAD

**Issue by ocafebabe** [Cetsoft/imcache#11]
I found a small issue with the cache hit ratio: if you ask for the hit ratio on a cache that never had a get operation called on it then you get a divide by zero exception!

```java
Cache cache = CacheBuilder.heapCache().build();                
cache.hitRatio();

java.lang.ArithmeticException: / by zero
	at com.cetsoft.imcache.cache.heap.HeapCache.hitRatio(HeapCache.java:136)
```

**Comment by yusufaytas** [comment]
I think this will probably apply to all the caches. A fix is needed for all of them.

**Comment by yusufaytas** [comment]
Fixed.
