### ISSUE TITLE
Offheap cache clearing is broken

### ISSUE THREAD

**Issue by ocafebabe** [Cetsoft/imcache#19]
Trying to clear an offheap cache results in an illegal state exception:

```java
Cache<Integer, Integer> cache =
    CacheBuilder.offHeapCache().storage(new OffHeapByteBufferStore(8388608, 10)).build();
for (int i=0; i<5; i++) {
    cache.put(i, i);
}
cache.clear();
```

And as soon as clear is called I get:

```java
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)
	at com.cetsoft.imcache.offheap.bytebuffer.OffHeapByteBufferStore.free(OffHeapByteBufferStore.java:225)
	at com.cetsoft.imcache.offheap.bytebuffer.OffHeapByteBufferStore.free(OffHeapByteBufferStore.java:214)
	at com.cetsoft.imcache.offheap.OffHeapCache.clear(OffHeapCache.java:254)
```

**Comment by yusufaytas** [comment]
First of all, thanks a lot reporting this bug. Here's the story. This is a bug related to available buffers. Whenever free them, we were trying to add freed buffer index to bounded queue which is already in the bounded  queue. So, we check buffer index and we clear it if available buffer don't contain index.

**Comment by yusufaytas** [comment]
We've fixed the bug with following commit. Closing the issue.
https://github.com/Cetsoft/imcache/commit/99191447d3ccb94e317bb73b0d2f66210806e889
