### ISSUE TITLE
Upgrade to Caffeine (from ConcurrentLinkedHashMap)

### ISSUE THREAD

**Issue by ben-manes** [Cetsoft/imcache#20]
[Caffeine](https://github.com/ben-manes/caffeine) is a Java 8 rewrite based on my experiences designing Guava's Cache and CLHM. Currently this project embeds an older version CLHM (probably `1.3.x`; latest is `1.4.2`). I'd recommend shading rather than embed libraries for easier upgrades.

Caffeine introduces a [near optimal](https://github.com/ben-manes/caffeine/wiki/Efficiency), novel eviction policy. This was shown to be particularly well suited for database, search, and web workloads. The new cache has better performance and numerous features.

**Comment by yusufaytas** [comment]
https://github.com/Cetsoft/imcache/pull/29
