### ISSUE TITLE
ImcacheType unicity/atomicity

### ISSUE THREAD

**Issue by ocafebabe** [Cetsoft/imcache#21]
I am having concerns about the use of the "volatile" keyword in the implementation of the ImcacheType class! Making ordinalCounter volatile garantuees its visibility but not its atomicity when it's incremented, indeed "++" is actually 3 distinct operations:

1) Read the integer to a local.
2) Increment the local.
3) Write the integer back out to the volatile field.

So based on that, if many threads are creating instances of this class I guess we could end up with multiple types with the same ordinal value no?

An easy alternative would be to replace the ordinalCounter with an AtomicInteger and use it like that: 
```java
ordinal = ordinalCounter.incrementAndGet();
```

**Comment by yusufaytas** [comment]
Agreed, @ocafebabe would you be interested in sending a merge request? Thanks.

**Comment by ocafebabe** [comment]
There you go!

**Comment by yusufaytas** [comment]
@ocafebabe Thanks a lot.
