### ISSUE TITLE
Can 't clear Off heap data

### ISSUE THREAD

**Issue by xyl1204** [Cetsoft/imcache#25]
1)I use a [cache.clear ()], but this method is not delete the data in memory
/*
     \* (non-Javadoc)
     \* 
     \* @see com.cetsoft.imcache.bytebuffer.ByteBuffer#free()
     */
    public void free() {
        try {
            java.lang.reflect.Field cleanerField = byteBuffer.getClass().getDeclaredField("cleaner");
            cleanerField.setAccessible(true);
            // Cleaner can force freeing of native memory by clean method
            sun.misc.Cleaner cleaner = (sun.misc.Cleaner) cleanerField.get(byteBuffer);
            cleaner.clean();
        } catch (Exception e) {
            throw new Error(e);
        }
    }
2)I also found a bug, [allocate (beta [] content] method will lead to can not add the data.
 protected Allocation allocate(byte[] payload) {
        int payloadLength = payload.length + POINTER_SIZE;
        int allocationOffset = offset.addAndGet(payloadLength);
        if (this.capacity < allocationOffset) {
            throw new BufferOverflowException();
        }
        Allocation allocation = new Allocation(allocationOffset - payloadLength, payloadLength);
        return allocation;
    }

**Comment by yusufaytas** [comment]
Could you please give some details. Why do you think there is a bug. Cleaner won't actually decrease the memory size, it's just cleaning the buffer.
