### ISSUE TITLE
Typo in "pupulator" and "LazyCachePupulator": Pupulator should be populator

### ISSUE THREAD

**Issue by hselvarajan** [Cetsoft/imcache#3]
The ```com.cetsoft.imcache.cache.pupulator``` package and ```com.cetsoft.imcache.cache.pupulator.LazyCachePupulator``` class have typos in the package and class names, respectively.

I assume your intent was to call them ```com.cetsoft.imcache.cache.populator``` and ```com.cetsoft.imcache.cache.populator.LazyCachePopulator```.

**Comment by yusufaytas** [comment]
Hello,

Thanks for opening up the issue. Would you be interested in fixing the issue?

Cheers,
Yusuf

**Comment by hselvarajan** [comment]
Certainly. I'll fix it and send you a pull request.

**Comment by yusufaytas** [comment]
Awesome, thanks
