### ISSUE TITLE
time expiration. 

### ISSUE THREAD

**Issue by ghost** [Cetsoft/imcache#6]
Is there a time expiration setting?

**Comment by yusufaytas** [comment]
In offheap cache settings, you can define eviction period. https://github.com/Cetsoft/imcache/blob/master/imcache-offheap/src/main/java/com/cetsoft/imcache/cache/offheap/OffHeapCache.java#L117 I believe we'll support timed eviction for redis and memcache. However, there's no timed eviction support for heap cache.

**Comment by Meboolean** [comment]
In offheap cache,the EvictionListener  is unuseful?

**Comment by yusufaytas** [comment]
@Meboolean it's not. Imcache always do size based eviction. It doesn't care about time.

**Comment by yusufaytas** [comment]
https://github.com/Cetsoft/imcache/pull/29
