### ISSUE TITLE
Cache clearing is broken

### ISSUE THREAD

**Issue by ocafebabe** [Cetsoft/imcache#8]
It seems that clearing a cache is currently broken (0.1.2 and 0.1.3-SNAPSHOT):

```java
Cache<String, Integer> cache = CacheBuilder.heapCache().build();
cache.put("1", 1);
cache.put("2", 2);
cache.clear();
```

And you get:

```java
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
	at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:405)
	at com.cetsoft.imcache.cache.heap.HeapCache.clear(HeapCache.java:121)
```

I looked at the code and the "clear" method implementation is faulty: you cannot remove a value from a map while looping over its keys...

**Comment by AdoHe** [comment]
@ocafebabe we will fix this as soon as possible.

**Comment by yusufaytas** [comment]
@AdoHe fixed the issue and we'll release another version with a few fixes.

**Comment by ocafebabe** [comment]
Cool thanks :)

**Comment by yusufaytas** [comment]
@ocafebabe can you please also send your pull request for singletonCacheCoordinator to add it to next release.

**Comment by ocafebabe** [comment]
Yes I'll try to do it this afternoon...

**Comment by yusufaytas** [comment]
awesome @ocafebabe, thanks a lot.

**Comment by yusufaytas** [comment]
I've fixed the problem and adjusted unit tests. Closing the issue.
